### ISSUE TITLE
Explanation for "Time for some hash brownies!" is insufficient

### ISSUE THREAD

**Issue by maniexx** [satwikkansal/wtfpython#10]
The current explanation seems to imply that any two values with equal hashes will take up the same slot in the dict. This is, fortunately, not true.
example:
```
>>> d = {}
>>> a = float('NaN')
>>> b = 0
>>> d[a] = 1
>>> d[b] = 2
>>> d
{nan: 1, 0: 2}
>>> hash(a) == hash(b)
True
```

The actual reason `0.0 `overwrites `0`, is that they are equal.

```
>>> 0.0 == 0
True
```
I don't quite know how to put all that concisely, without losing the interesting lesson about hash values.
Any suggestions welcome.

**Comment by satwikkansal** [comment]
Yeah, I missed a very important detail. I'll try to come up with a more concise explanation.

**Comment by topin89** [comment]
There is also this:
```
>>> d[a]
1
>>> d[float('NaN')]
KeyError: nan
>>> a==a
False
```

**Comment by maniexx** [comment]
@topin89 oh yeah that is NaN being NaN - a whole other thing, so perhaps I didn't choose the best example, but that was what came to mind.

**Comment by satwikkansal** [comment]
@maniexx Added a more accurate explanation for the example. Feel free to reopen the issue if you think it's still insufficient or incorrect :)

**Comment by maniexx** [comment]
@satwikkansal it's great!
