### ISSUE TITLE
isinstance loop

### ISSUE THREAD

**Issue by MuseBoy** [satwikkansal/wtfpython#101]
```Python
>>>isinstance(type,object)
True
>>>isinstance(object,type)
True
```

**Comment by satwikkansal** [comment]
Awesome, I was looking to introduce something related to Metaclasses, I think this could be a nice-simple snippet to start with.

**Comment by satwikkansal** [comment]
@MuseBoy Added, thanks for the suggestion :) You can check the above commit and let me know if something's incorrect or missing.
