### ISSUE TITLE
What is the difference?

### ISSUE THREAD

**Issue by XiaXuehai** [satwikkansal/wtfpython#103]
![image](https://user-images.githubusercontent.com/11585321/49490985-672ed600-f88d-11e8-8367-697ebae01afe.png)
![image](https://user-images.githubusercontent.com/11585321/49491004-79a90f80-f88d-11e8-8de4-03eb682afb02.png)
python3.6.3

**Comment by Delta456** [comment]
In 2nd one they are not in same memory allocation.

**Comment by rwithik** [comment]
Try printing the id of a and b in both the cases, both times. You'll see that the id's of a and b are same in the second case of the program. Which shows that both the variables point to the same location. My guess is that while running the program, it treats it as  
`a = 'wtf!'; b = 'wtf!' `  
which would make it point to the same location.
