### ISSUE TITLE
Timeit issue

### ISSUE THREAD

**Issue by henryiii** [satwikkansal/wtfpython#106]
I believe the code in `Let's make a giant string!` is incorrect; that's not how you use the timeit module. (I would normally use IPython's `%%timeit` magic). You have to give the function to timeit in some way where it does not evaluate the function before it gets to the timeit call!

Something like this would work:

```python
timeit.timeit('add_string_with_plus(10000)', number=1000, globals=globals())
```

**Comment by satwikkansal** [comment]
Fixed :)
