### ISSUE TITLE
Python 2: True/False literal

### ISSUE THREAD

**Issue by mishaturnbull** [satwikkansal/wtfpython#108]
**In Python 2** (tested 2.7.15+ on Debian), the boolean operators `True` and `False` are in fact not literals, and can be reassigned.  Unfortunately, I can't remember where I found this, but I've used it a few times to mess with people's code.  Good fun :)

```python
>>> True
True
>>> False
False
>>> True == False
False  # as expected!
>>> True = False  # Note, only 1 '='.  This is assignment!
>>> True
False    # !!
>>> True == False  # normally, False.  Now, we're expecting...
True
```

The reverse is also possible:
```python
>>> False = True  # assignment, not equality check
>>> if False: print("Hello World!")    # this should never work.
...
Hello World!
```

~~Un~~fortunately, this behavior was removed in Python 3 by setting `True` and `False` to be literals.  I can't seem to find this alluded to in the list; let me know if it's worthy of a PR.

**Comment by satwikkansal** [comment]
@mishaturnbull Yes, it's definitely worth a PR. We already have a few WTFs that only work on specific versions of python, so there is no issue adding more as long as they're interesting.

**Comment by satwikkansal** [comment]
No problem, Looking forward to it!

**Comment by mishaturnbull** [comment]
Finally got to the PR, and... found the example already in the list!  I must've missed it the first time around.

https://github.com/satwikkansal/wtfpython#-when-true-is-actually-false
