### ISSUE TITLE
New example

### ISSUE THREAD

**Issue by rwithik** [satwikkansal/wtfpython#111]
```py
 >>> x = 0.1
 >>> y = 0.2
 >>> x + y
 0.30000000000000004
 ```
 ```py
 >>> .2 + .1
 0.30000000000000004
 ```
 ```py
 >>> .2 + .1 == .3
 False
 ```
This is not a python exclusive phenomenon. So, is it still worthy to have an example for itself?

(I can submit the pull request over the weekend if its approved.)

**Comment by satwikkansal** [comment]
I don't think wtfpython is the right place for this. From my experience, it usually infuriates experienced programmers when they see examples like this in wtfpython.

**Comment by rwithik** [comment]
Fair enough. 
I'll close this issue then.
