### ISSUE TITLE
Add a quick link

### ISSUE THREAD

**Issue by leisurelicht** [satwikkansal/wtfpython#112]
Hello, I was translated the project to chinese.
Can you add a quick link in the front of readme content to help others quickly get it.
like:
```
<p align="center">
<a href="https://github.com/leisurelicht/wtfpython-cn">中文</a>
</p>
```

**Comment by satwikkansal** [comment]
Thanks!

**Comment by leisurelicht** [comment]
thanks, This is really an interesting project. hope you can make it better.
