### ISSUE TITLE
Why output of "id(WTF()) is id(WTF())" is False

### ISSUE THREAD

**Issue by acejerry** [satwikkansal/wtfpython#113]
![image](https://user-images.githubusercontent.com/8581684/50733942-7e851a00-11d1-11e9-9d5f-9c43973c6f42.png)

**Comment by acejerry** [comment]
Python version is 3.6.2
![image](https://user-images.githubusercontent.com/8581684/50733961-ce63e100-11d1-11e9-8ffe-3f5dd272387d.png)

**Comment by lypch** [comment]
In your code, WTF() is used to tell python to create a new instance of WTF class. so WTF() was executed twice and two instances with different memory address were created.  so the result is false.

**Comment by Ricocotam** [comment]
The object is created twice because once the first `id(WTF())` is executed, the object is destroyed because not assigned, only the id is stored. Then you build a second object that has the same id, probably because you just destroyed the exact space you needed in your process
