### ISSUE TITLE
More explanation for Brace yourself! 

### ISSUE THREAD

**Issue by zhe-li** [satwikkansal/wtfpython#114]
Hi,

Regarding 'Brace yourself!', I think it worth adding more explanation for where 'SyntaxError: not a chance' comes from and how it works.

I checked `__future__` code, but could not find any 'braces'. I was wondering where the response 'SyntaxError: not a chance' comes from. Then I found answer from stackoverflow in the link below.

https://stackoverflow.com/questions/21125228/where-is-the-from-future-import-braces-code/21125305#21125305

Both the answer and the first comment of the answer are helpful to understand what happens under the hood. So I would suggest to them to  'Brace yourself!'

**Comment by satwikkansal** [comment]
@zhe-li Added, thanks for the suggestion :) You can check the above commit and let me know if something's incorrect or missing.
