### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by nagayev** [satwikkansal/wtfpython#118]
I think I can translate readme.md from English to Russian.

**Comment by satwikkansal** [comment]
Hi @nagayev, that'd be awesome. Please go ahead, and let me know if you need any help.

**Comment by nagayev** [comment]
@satwikkansal good!

**Comment by satwikkansal** [comment]
Hi @nagayev, Still working on the translation?

**Comment by nagayev** [comment]
@satwikkansal yep!
I'll push the first version tomorrow.

**Comment by satwikkansal** [comment]
Awesome @nagayev, looking forward to it.

**Comment by nagayev** [comment]
@satwikkansal 
This version is on very early stage,sorry.
I'll improve this on my May's holidays.
https://gist.github.com/nagayev/9f3cb1dca089479b10579f97f0a378c1

**Comment by satwikkansal** [comment]
@nagayev No worries, let me know when it's done :)

**Comment by nagayev** [comment]
@satwikkansal okey)

**Comment by nagayev** [comment]
[EN]
For Russian speaking people:
If you want, you can contribute to Russian translation gist:
https://gist.github.com/nagayev/9f3cb1dca089479b10579f97f0a378c1
[RU]
Ребят, если внесете вклад в этот gist будет круто!

**Comment by satwikkansal** [comment]
Hi @nagayev 

Just checking, were you able to make any progress with the Russian translation?

**Comment by nagayev** [comment]
@satwikkansal No.
I work on my own projects(

**Comment by cuamckuu** [comment]
Started to work on it. Introduction and some first snippets are ready

**Comment by satwikkansal** [comment]
Awesome, let me know if you need any help.

**Comment by nagayev** [comment]
@cuamckuu You can use my gist.
Some threads were translated.
Mb I can help you.

**Comment by cuamckuu** [comment]
About 50% of raw translation is ready, first version should be ready soon

**Comment by nagayev** [comment]
@cuamckuu Nice news!
But where we can view your work?
Your fork looks as the original repo.

**Comment by cuamckuu** [comment]
Pushed it now, https://github.com/cuamckuu/wtfpython-ru

**Comment by nagayev** [comment]
@cuamckuu Thanks.

**Comment by ansuleymanova** [comment]
@satwikkansal Hey! I'd love to contribute to Russian translation, but nagayev's fork is really behind. How would you like me to approach this?

**Comment by 1033786579** [comment]
您发给我的信件已经收到。我会尽快查看邮件。谢谢!

**Comment by satwikkansal** [comment]
Hey @ansuleymanova !

Thanks for considering to translate :) I understand that other forks are quite outdated, and I think it makes sense to start afresh. You can check out this [link](https://github.com/satwikkansal/wtfpython/issues?q=label%3Atranslation+) to see how other people did it. And if you have any questions, I'm happy to help!

**Comment by 1interceptor3** [comment]
@satwikkansal hello, i emailed you. I'd better start translating from the beginning. how do I do it right, make a fork and change it?

**Comment by 1033786579** [comment]
您发给我的信件已经收到。我会尽快查看邮件。谢谢!

**Comment by satwikkansal** [comment]
Hi @1interceptor3 , yes you can make a fork and do the translation there. You can see how other people have done it in the old issues https://github.com/satwikkansal/wtfpython/issues?q=is%3Aissue+label%3Atranslation 

If you're stuck on anything or have any questions, you can let me know :)

**Comment by satwikkansal** [comment]
Closed in favor of https://github.com/satwikkansal/wtfpython/issues/297
