### ISSUE TITLE
Careless zips of iterators

### ISSUE THREAD

**Issue by pmjpawelec** [satwikkansal/wtfpython#121]
Real life lesson. It boggles the mind of many people I show to. Please tell me if this is good enough to add to the wtfpython.

Let's zip some numbers and characters. 

```py
>>> a = iter([1,2,3,4,5])
>>> b = ['a', 'b', 'c']
>>> c = ['d', 'e']
>>> print(list(zip(a,b)))
>>> print(list(zip(a,c)))
[(1, 'a'), (2, 'b'), (3, 'c')]
[(5, 'd')]
```

Somehow the number 4 is lost in the process.

Explanation: The first `zip` consumes one element (the number 4) from the iterator before realizing it has no matching element from the second list. The element was not "peeked", but taken and it can't be pushed back to a python iterator.

Note: This examples "works" with the reverse order of arguments in the zip.

**Comment by satwikkansal** [comment]
@pmjpawelec Thanks for suggesting this, I'll definitely add it in the next iteration.
