### ISSUE TITLE
Ex)The link for Let's Mangle ^ in `3.0` branch is broken 

### ISSUE THREAD

**Issue by josephwon0310** [satwikkansal/wtfpython#130]
The link to the corresponding explanation is broken as well.

**Comment by josephwon0310** [comment]
Also, this is a subjective suggestion: adding links to explanations for each examples seems a bit pointless to me. It rather convolutes the document and doesn't help with readability.(This is a personal opinion!) @satwikkansal

**Comment by satwikkansal** [comment]
Fixed, the toc generator I was using previously had some bug it seems. 

> Also, this is a subjective suggestion: adding links to explanations for each examples seems a bit pointless to me. It rather convolutes the document and doesn't help with readability.(This is a personal opinion!)

Fixed this as well.
