### ISSUE TITLE
there is so many problems in your project

### ISSUE THREAD

**Issue by JieshuaiCui** [satwikkansal/wtfpython#131]
as like the title,your pro has so many mistakes.So i can't stand to make these right.In fact,you don't has so much knowledges in assembly language and don't be familiar with the python.

**Comment by Jamim** [comment]
What are you talking about?

**Comment by Ricocotam** [comment]
From the time this repo has been on, plenty mistakes were made from all of us and most of them have been fixed. If you find one just tell it's wrong and explain why. If you don't understand something and feel an explanation isn't clear just ask for more details.

But this comment is pretty much useless and has as only purpose trolling

**Comment by satwikkansal** [comment]
> as like the title,your pro has so many mistakes.So i can't stand to make these right.In fact,you don't has so much knowledges in assembly language and don't be familiar with the python.

Hey @JieshuaiCui, If possible, can you be more specific about the "mistakes" that you are talking about? I know that there's a possiblity of having gaps in my understanding, and rightly so, these have been pointed out by readers in the [issues](https://github.com/satwikkansal/wtfpython/issues?q=is%3Aissue+is%3Aclosed) they created. 

I've tried my best to work upon them to put a simple and clear picture of what's happening, and if you can point out the mistakes you're referring to I'll do the same for them. This is how I've been maintaining the project so far, I'm no super-expert in Python, I just try to keep enhancing the understanding of the language through various means (and wtf-like design is nothing but a fun element to all this).

**Comment by josephwon0310** [comment]
I don't think there is any point leaving this issue open and dangle without a clear purpose. It'll be better to have a dedicated thread for healthier discussion regarding the examples.

**Comment by satwikkansal** [comment]
Makes sense, @JieshuaiCui if you feel some of the examples are incorrect or need improvement, please feel free to re-open the issue or create new issues. Closing this one for now.
