### ISSUE TITLE
String Interning

### ISSUE THREAD

**Issue by pkkdguy** [satwikkansal/wtfpython#135]
`a,b = "wtf!", "wtf!"`
`a is b # This returns False`

**Comment by Jamim** [comment]
I've just checked this and found that the behavior was changed in Python 3.7.

```bash
$ python2.7 -c 'a, b = "wtf!", "wtf!"; print(a is b)'
True
$ python3.6 -c 'a, b = "wtf!", "wtf!"; print(a is b)'
True
$ python3.7 -c 'a, b = "wtf!", "wtf!"; print(a is b)'
False
```

**Comment by satwikkansal** [comment]
Yeah, there's a note regarding this in 3.0 branch (not merged to master yet), https://github.com/satwikkansal/wtfpython/commit/bf967b0332ff2c5d645ab4f420f1c24a9b0702db

**Comment by satwikkansal** [comment]
Also related: https://github.com/satwikkansal/wtfpython/issues/100

**Comment by satwikkansal** [comment]
Closing this in favor of other issue.
