### ISSUE TITLE
Is copy or reference in self recursion?

### ISSUE THREAD

**Issue by daidai21** [satwikkansal/wtfpython#137]
Hello, I not found in this repository about this grammar. so, I open this issue.
My CPython version is 3.7.1

- list recursion (reference )

```python
class C:
    def f1(self, a):
        if a[0][0] == 0:
            return a
        else:
            a[0][0] -= 1

        self.f1(a)
        return a


print(C().f1([[5, 2],[3, 4]]))
```
result:
```bash
>>> [[0, 2], [3, 4]]
```

- variable recursion (copy)

```python
class C:
    def f1(self, a):
        if a == 0:
            return a
        else:
            a -= 1

        self.f1(a)
        return a


print(C().f1(3))
```
result
```bash
>>> 2
```

Just defining functions is the same.
Thank you.

**Comment by satwikkansal** [comment]
Great, thanks for suggesting this @daidai21 

Will definitely add this in the next iteration.
