### ISSUE TITLE
example2

### ISSUE THREAD

**Issue by Yukti-09** [satwikkansal/wtfpython#150]
>>> int(1.99)
1
>>> int(7.7)
7
>>> int(7.7) + 1 
8
The above does not round up

**Comment by agathavekris** [comment]
Hey Yukti, if you import math and use the ceil() function it rounds up. Is there somewhere in the documentation that says otherwise? Cuz if so I'd love to change it!

Here's your code with the ceil() function: 

`import math as m`

`print(m.ceil(1.99))`
`print(m.ceil(7.7))`
`print(m.ceil(7.7 + 1))`

**Comment by satwikkansal** [comment]
Closing this in the favor of above comment. 

The expected behavior of `int` casting is to truncate the floating point which is exactly what's being done.
