### ISSUE TITLE
Constant folding example is not correct in Python3

### ISSUE THREAD

**Issue by KyleXie** [satwikkansal/wtfpython#153]
In Python2, the result is:
```
>>> 'a' * 21 is 'aaaaaaaaaaaaaaaaaaaaa'
False
```

But in Python3.7.4(I didn't try other versions), it's:

```
>>> 'a' * 21 is 'aaaaaaaaaaaaaaaaaaaaa'
True
```

Which is not like the one described in `Strings can be tricky sometimes` section. Maybe we should update that section to make it clear?

**Comment by satwikkansal** [comment]
Hi @KyleXie 

Yeah, you're right. I have an explanation for this in my [3.0 branch](https://github.com/satwikkansal/wtfpython/tree/3.0) (next revision of wtfpython). 

> In Python 3.7, Constant folding was moved out from peephole optimizer to the new AST optimizer with some change in logic as well, so the third snippet doesn't work for Python 3.7. You can read more about the change here.

Will be synced with the master branch too in the coming week.
