### ISSUE TITLE
Possible Typo in Strings can be tricky sometimes

### ISSUE THREAD

**Issue by buttercrab** [satwikkansal/wtfpython#165]
In line 349, it says:

> + When `a` and `b` are set to `"wtf!"` in the same line, the Python interpreter creates a new object, then references the second variable at the same time. If you do it on separate lines, it doesn't "know" that there's already `wtf!` as an object (because `"wtf!"` is not implicitly interned as per the facts mentioned above). It's a compile-time optimization. This optimization doesn't apply to 3.7.x versions of CPython (check this [issue](https://github.com/satwikkansal/wtfpython/issues/100) for more discussion).

But it looks like second `wtf!` needs parenthesis.

**Comment by satwikkansal** [comment]
Hi @buttercrab, 

I'm not able to understand. Do you mind pointing out what should be the correct sentence according to you?

**Comment by buttercrab** [comment]
I think It should be:

> + When `a` and `b` are set to `"wtf!"` in the same line, the Python interpreter creates a new object, then references the second variable at the same time. If you do it on separate lines, it doesn't "know" that there's already `"wtf!"` as an object (because `"wtf!"` is not implicitly interned as per the facts mentioned above). It's a compile-time optimization. This optimization doesn't apply to 3.7.x versions of CPython (check this [issue](https://github.com/satwikkansal/wtfpython/issues/100) for more discussion).

on the second `"wtf!"`. All the other strings have brackets so I think this is a typo.
