### ISSUE TITLE
A kind suggestion

### ISSUE THREAD

**Issue by stefanos82** [satwikkansal/wtfPython#17]
Can you please make it explicit which Python version produces these "what the heck" results?

I have tested the very first example, named `Skipping Lines` and produces `32` instead of `11`.

This behavior you produce is for `Python 2.7`.

**Comment by satwikkansal** [comment]
The python version is mentioned over [here](https://github.com/satwikkansal/wtfPython/blame/master/README.md#L117) (it's `3.4.5`)

**Comment by satwikkansal** [comment]
You won't be able to reproduce the first example with a standard keyboard. A copy-paste should work https://github.com/satwikkansal/wtfPython/blame/master/README.md#L174

**Comment by satwikkansal** [comment]
Thanks, for reporting this, I'll update these details so that they are clearly visible :+1:

**Comment by satwikkansal** [comment]
@stefanos82 I've addressed your suggestions in 82bbded commit. If that still doesn't work for you, feel free to reopen the issue :)

**Comment by stefanos82** [comment]
Very nice. I will test the entire thing as much as possible.

By the way, you have a typo; it should be `file/shell`, but you mistype an extra `l` that end of the the word.

Cheers.

**Comment by satwikkansal** [comment]
Ugh.. another typo! Will fix it asap. Thanks for letting me know.

Cheers!
