### ISSUE TITLE
typo in Strings and backslashes

### ISSUE THREAD

**Issue by matejcik** [satwikkansal/wtfpython#173]
the [following](https://github.com/satwikkansal/wtfpython/blob/master/README.md#L1225-L1226) is untrue:
```
>>> print(r"\\n")
'\\\\n'
```

it should be one of the following:
```
>>> print(r"\\n")
\\n
>>> print(repr(r"\\n"))
'\\\\n'
```

**Comment by Haksell** [comment]
Seconded.

And even better,
```
>>> repr(r"\\n")
"'\\\\\\\\n'"```

**Comment by amitShindeGit** [comment]
Thank you for pointing this out,made a PR for this.Happy to help.

**Comment by satwikkansal** [comment]
Thanks @amitShindeGit 

Closing the issue.
