### ISSUE TITLE
Can I translate it into Chinese?

### ISSUE THREAD

**Issue by tmpbook** [satwikkansal/wtfPython#18]
I just forked it.

**Comment by satwikkansal** [comment]
Hey @tmpbook, sure. The project WTFPL licensed, you can do whatever you want to (though just a simple reference to this project in your work will be highly appreciated). Let me know if you need any other help regarding this :)

**Comment by tmpbook** [comment]
@satwikkansal Sure, thank you. 😝

**Comment by satwikkansal** [comment]
Okay, closing this for now. Feel free to open a new issue if required :+1:

**Comment by amoghskulkarni** [comment]
Sorry for being a grammar nazi, but the grammatically correct English will be "Do *Whatever* The Fuck You Want To Public License". :sweat_smile:

Amazing work by the way! Keep going! 👍

**Comment by satwikkansal** [comment]
Haha, Thanks :)
