### ISSUE TITLE
Modifying a dictionary while iterating over it

### ISSUE THREAD

**Issue by Pradhvan** [satwikkansal/wtfpython#182]
I was trying the modify a dictionary by deleting its key with `del dictonary[key] ` if the condition is met while iterating over the whole dictionary. During the process, I saw an error `RuntimeError: dictionary keys changed during iteration`. 

As the section[0] suggested the error only pops up in Python 3.8 onwards. I got the error in Python 3.7.6. 

So I am assuming the section needs to be updated. I would be happy to submit a PR if I am right and the docs need to be updated.  

[0]https://github.com/satwikkansal/wtfpython#-modifying-a-dictionary-while-iterating-over-it

**Comment by satwikkansal** [comment]
yeah, that requires an update.
