### ISSUE TITLE
The out of scope variable: mention `nonlocal`

### ISSUE THREAD

**Issue by actionless** [satwikkansal/wtfpython#193]
https://github.com/satwikkansal/wtfpython#-the-out-of-scope-variable

> To modify the outer scope variable a in another_func, use global keyword.

https://docs.python.org/3/reference/simple_stmts.html#grammar-token-nonlocal-stmt

**Comment by diptangsu** [comment]
I would love to add this to this repo!

**Comment by satwikkansal** [comment]
Sure @diptangsu, Feel free to submit a PR for this.

**Comment by diptangsu** [comment]
I have submitted a [PR](https://github.com/satwikkansal/wtfpython/pull/228). I also made some extra changes. Let me know if I need to change something, I'll add the required changes and add another commit!

**Comment by satwikkansal** [comment]
Thank you @diptangsu for going beyond just mentioning `nonlocal` and adding a nice example for it. Really appreciate it :)
