### ISSUE TITLE
Slight wording issue in README

### ISSUE THREAD

**Issue by kirbyfan64** [satwikkansal/wtfPython#2]
> If `join()` is a method on a string then it can operate on any iterable (list, tuple, iterators). If it were a method on a list, it'd have to be implemented separately by every type. Also, it doesn't make much sense to put a string-specific method on a generic list.

> Also, it's string specific, and it sounds wrong to put a string-specific method on a generic list.

Notice the string-specific part is duplicated in the last two sentences.

**Comment by satwikkansal** [comment]
yeah, thanks for reporting :)

**Comment by satwikkansal** [comment]
Fixed :+1:
