### ISSUE TITLE
Prehistory

### ISSUE THREAD

**Issue by MarcinCiura** [satwikkansal/wtfpython#206]
Hi Satwik! If you are interested in antediluvian times, check out https://github.com/MarcinCiura/6-gotchas :)
Cheers!

**Comment by satwikkansal** [comment]
Oh nice, I was wondering what to do today, and I found this :)

**Comment by nifadyev** [comment]
Hey @satwikkansal , link is dead and the issue is not related to project. Maybe close this one?
