### ISSUE TITLE
Dividing in python

### ISSUE THREAD

**Issue by Yukti-09** [satwikkansal/wtfpython#213]
In python 2
```
print(35/6)
```
OUTPUT:
```
5
```
In python 3
```
print(35/6)
```
OUTPUT:
```
5.833333333333333 
```

**Comment by Yukti-09** [comment]
@satwikkansal

**Comment by satwikkansal** [comment]
This one is a well-known change between Python 2 to Python 3, readers would rather be annoyed if it is included at this stage. Moreover, we might be dropping Python 2 content in the future (see https://github.com/satwikkansal/wtfpython/issues/179). 

So closing this due to the above reasons.
