### ISSUE TITLE
Use of_ to get previous value

### ISSUE THREAD

**Issue by Yukti-09** [satwikkansal/wtfpython#214]
We can make use of '_' to get the previous value

```
>>> 4*7
28
>>> 7*_
196
```
@satwikkansal

**Comment by satwikkansal** [comment]
This is covered in the "Stubborn del operator" example,

<img width="861" alt="image" src="https://user-images.githubusercontent.com/10217535/88773131-5f791f00-d19f-11ea-8c5c-8f2c38b6ae06.png">
