### ISSUE TITLE
Why there is a 💡 before some of the "Explanation".

### ISSUE THREAD

**Issue by tmpbook** [satwikkansal/wtfpython#22]
What is the different?

https://github.com/satwikkansal/wtfpython#-explanation
https://github.com/satwikkansal/wtfpython#explanation

**Comment by satwikkansal** [comment]
Ah, I like that :bulb: character, actually it was supposed be before all of the "Explanation" but I think it got missed in some find replace thing I was doing. Will fix it asap. Thanks for reporting.
