### ISSUE TITLE
Eager execution of function parameters with mutable default arguments

### ISSUE THREAD

**Issue by diptangsu** [satwikkansal/wtfpython#229]
```py
>>> def func(a=[]):
...   a.append(len(a))
...   return a
... 
>>> print(func(), func())
[0, 1] [0, 1]
```
This is not a weird behaviour but might seem tricky to guess the output of. One might think the output would be
```py
[0] [0, 1]
```

Would you like me to add this somewhere along with the explanation?

**Comment by satwikkansal** [comment]
Default mutable arguments are  already covered in https://github.com/satwikkansal/wtfpython#-beware-of-default-mutable-arguments

**Comment by diptangsu** [comment]
Yep! I know. I've read the whole thing xD

It's just that all the people I've shown this example to, have answered it wrong. This can be a potential follow up snippet to the mutable default args one. It's not the same since another concept is at play here, which is eager execution of function params, which happens in most languages but has potential to lead to some weird use cases, like in the example above.

**Comment by satwikkansal** [comment]
> eager execution of function params

I'm not sure what this means in the context of the example you shared. Since the function returns `a` (which is shared across function calls), we're just printing the value twice. I'm not able to see an unexpected behavior here (apart from the default mutable argument catch).

**Comment by diptangsu** [comment]
Yup!

It's not unexpected behavior at all. It's just an interesting example according to me because many people will get it wrong. It's obvious to you because you understand python well. It's also not a python specific issue based on what the reason for this is. 

I'll close this issue.
