### ISSUE TITLE
explain wrong for class var https://github.com/satwikkansal/wtfpython#-explanation-22

### ISSUE THREAD

**Issue by vwas2** [satwikkansal/wtfpython#230]
```
class A:
    x = 1

class B(A):
    pass

class C(A):
    pass

print(A.x, B.x)
A.x = 2
print(A.x, B.x, C.x)
B.x += 1
print(A.x, B.x, C.x)
``` 

> 1 1
> 2 2 2
> 2 3 2

explanation is wrong: if in object-inplace modify applies then third output should be 3 3 3, since B.x defaults to class var (B itself does not have x) and would increment the common x of A and C as well. but it doesnt

the `B.x += 1` is equiv to `B.x = B.x + 1`, thus B gets a new class var, see `dir(B)` and would propagate to `C(B)`

**Comment by Jongy** [comment]
> explanation is wrong: if in object-inplace modify applies then third output should be 3 3 3, since B.x defaults to class var (B itself does not have x) and would increment the common x of A and C as well. but it doesnt

It is mentioned (perhaps too subtly) that "the `+=` operator modifies the *mutable* object in-place". Integers are immutable. They do not implement inplace addition. The difference between classes implementing inplace add and non-inplace add can be demonstrated by this:
```
class Inplace:
    def __init__(self, n):
        self.n = n

    def __iadd__(self, other):
        self.n += other.n
        return self


class A:
    x = Inplace(1)


class B(A):
    pass


B.x += Inplace(1)
print(A.x.n, B.x.n)
# prints 2, 2


class NotInplace:
    def __init__(self, n):
        self.n = n

    def __add__(self, other):
        return NotInplace(self.n + other.n)


class C:
    x = NotInplace(1)


class D(C):
    pass


D.x += NotInplace(1)
print(C.x.n, D.x.n)
# prints 1, 2
```

Do note that a value is still assigned to `B`'s `__dict__`, it's just that this value is the same object as `A.x`: `A.x is B.x` is `True`, because `__iadd__` returns `self`.

**Comment by vwas2** [comment]
to sum up: 
mutable or not, in any case `+` or `+=` the assignment adds a __dict__ key; 
if mutable dereference and mutate (eg [1,]) :P, if immutable (eg 1)  create one that fits the result;

**Comment by Jongy** [comment]
> to sum up:
> mutable or not, in any case `+` or `+=` the assignment adds a `__dict__` key;
> if mutable dereference and mutate (eg [1,]) :P, if immutable (eg 1) create one that fits the result;

Yup, that's right :)
