### ISSUE TITLE
Add translation for [KOREAN]

### ISSUE THREAD

**Issue by fgo0615** [satwikkansal/wtfpython#242]
Expected time to finish: [3] weeks. I'll start working on it from [2020/11/21].

**Comment by satwikkansal** [comment]
Hey @fgo0615, that's nice to know :) Feel free to check out https://github.com/satwikkansal/wtfpython/issues/128

A couple of people have attempted it previously, so you can probably build upon their work.

**Comment by fgo0615** [comment]
Oh I think @buttercrab finished this issue. So I close this issue. Thank you for your kindness.
