### ISSUE TITLE
Add translation for [Persian(Farsi)]

### ISSUE THREAD

**Issue by alirahimifachr** [satwikkansal/wtfpython#246]
hi,
if is it possible, i will translate this Repo to Persian.
do you have a advice for me?
thanks
arf

**Comment by satwikkansal** [comment]
Hi @alirahimifachr 

Sure, feel free to translate at your own pace. 

> do you have a advice for me?

Nothing specific as such, make sure to enjoy and learn as you go :) 

w.r.t implementation, you can check out the existing translation issues to check how other contributors have done it https://github.com/satwikkansal/wtfpython/labels/translation
