### ISSUE TITLE
Add translation for Spanish

### ISSUE THREAD

**Issue by JoseDeFreitas** [satwikkansal/wtfpython#252]
Expected time to finish: 1 week. I'll start working on it when I get a response to this issue.

Hello 👋.
I'm a native Spanish speaker who has previously contributed to the translation of other open-source projects from English to Spanish. I found this project and thought it was interesting (especially for me as Python is my main programming language!) so it'd be a pleasure working on the translation of this.
If you want this translation, please give me indications (if any) about the translation process.
Thank you in advance!

**Comment by satwikkansal** [comment]
Hi @JoseDeFreitas 

Thanks for considering translating this project :)

You can check out the existing translation issues to see how other contributors have done it https://github.com/satwikkansal/wtfpython/labels/translation

As long as you keep the example-ids (in the readme) intact, there shouldn't be much to worry about.

**Comment by JoseDeFreitas** [comment]
Alright! I'll start working on it then. Thank you @satwikkansal!

**Comment by cajotafer** [comment]
Hi @JoseDeFreitas , I would like to help on this. Is there any way I could join?

**Comment by JoseDeFreitas** [comment]
Hello @cajotafer!

See, I forked this repository (following the same thing the contributors for other languages did). This is my fork: https://github.com/JoseDeFreitas/wtfpython. I'm translating the text from the README file on the `master` branch (I'm at the line 708 and I skipped the "Table of Contents" section in order to translate that later so I can be more careful to match the titles/subtitles and the links).

I'd really like your help, so if you want you can open pull requests in there. Or, maybe better, I can give you collaborator access so you can work on it freely. Let me know any other thing. You can also contact me by [my Twitter](https://twitter.com/JoseDeF32503298) or my Discord (Jose#7947) for an easier conversation.
