### ISSUE TITLE
Is this normal behaviour in CLI mode?

### ISSUE THREAD

**Issue by hp77-creator** [satwikkansal/wtfpython#272]
![wtfpython-issue](https://user-images.githubusercontent.com/24816726/130742424-32f6f90d-ef85-4075-83b6-9b3f5db3af35.png)
I installed the python package and ran the command and this is what I see!

**Comment by akdhd9** [comment]
د

**Comment by nifadyev** [comment]
Hey @satwikkansal , shall this issue be closed due to #345 ?
