### ISSUE TITLE
Calling the function without calling it

### ISSUE THREAD

**Issue by AkshitMehra1** [satwikkansal/wtfpython#273]
### ▶ Calling the function without calling it 

Make a file test.py
Add the following code
```py
def print_HelloWorld():
    print("Hello World")
print_HelloWorld()
print("Hello")
```

Make another file called try.py
Add the following code and then run this file
```py
import test
```
**Output**
>>> Hello World
>>> Hello

See without even calling the function we get the ouput.

#### 💡 Explanation:
This is the magic of import statement in python. Whenever we import a file all the code that is outside of main runs. This is why whatever we write in test.py it will run in when we are importing the file to any other program.
To overcome this, we use:
```py
if __name__=='_main__':
```
and then write everything in the main function. This will stop running the code that is in the imported file.

We can change the test.py file to 
  ```py
def print_HelloWorld():
    print("Hello World")
if __name__=="__main__":
    print_HelloWorld()
    print("Hello")
  ```
**Output**
 ```py
>>>
  ```
Now we get the desired result and nothing is called when we import the test.py file.

**Comment by IamMusavaRibica** [comment]
I don't really understand this one, you are literally calling a function here
![image](https://user-images.githubusercontent.com/65848142/148663458-1d060c7a-d146-4a48-b848-586f9f69b0bb.png)

**Comment by AkshitMehra1** [comment]
> I don't really understand this one, you are literally calling a function here ![image](https://user-images.githubusercontent.com/65848142/148663458-1d060c7a-d146-4a48-b848-586f9f69b0bb.png)

Actually, I am not running this file. I ran another file in which this file is imported and this code executes automatically.

**Comment by sebix** [comment]
> Actually, I am not running this file. I ran another file in which this file is imported and this code executes automatically.

That is absolutely expected behaviour. Code is executed upon import.

**Comment by IamMusavaRibica** [comment]
Exactly. And the output goes to the main file's sys.stdout, not anywhere else
