### ISSUE TITLE
Add Translation for Language HINDI

### ISSUE THREAD

**Issue by ankitbourasi0** [satwikkansal/wtfpython#285]
Expected time to finish: [6] weeks. I'll start working on it on [24/04/22].

**Comment by 1033786579** [comment]
您发给我的信件已经收到。我会尽快查看邮件。谢谢!

**Comment by satwikkansal** [comment]
Thanks, @ankitbourasi0 ! let me know in case you need any help. You can check out issues of existing translations for reference.

**Comment by nifadyev** [comment]
Hey @ankitbourasi0 , are you still interested in making the translation?

**Comment by nifadyev** [comment]
Hey @satwikkansal , don't you mind closing this issue? I guess we should create discussion with a list of missing translations and add Hindi to this list

**Comment by satwikkansal** [comment]
Marking it as closed in favour of moving to a discussion in future.
