### ISSUE TITLE
Removal of the Spanish translation

### ISSUE THREAD

**Issue by JoseDeFreitas** [satwikkansal/wtfpython#287]
Hello. For personal reasons, I decided to delete the repository with the Spanish translation I made (see PR #252). The link in the README file now points to a 404 error page. Nonetheless, I saved the page in web.archive.org, if you want to copy and paste it in another repository or file ([link here](https://web.archive.org/web/20220511161045/https://github.com/JoseDeFreitas/wtfpython-es)). Sorry for the inconvenient!

**Comment by 1033786579** [comment]
您发给我的信件已经收到。我会尽快查看邮件。谢谢!
