### ISSUE TITLE
If you could give the reason why this behaviour it would be much better, 

### ISSUE THREAD

**Issue by kallipattti** [satwikkansal/wtfpython#288]
If you could give the reason why this behaviour it would be much better,  I could not see any reason why that output is.

-A

**Comment by kallipattti** [comment]
Let the reply be in english if possible

**Comment by longqzh** [comment]
It's just a bot

**Comment by yash-601** [comment]
Can you elaborate your issue?

**Comment by nifadyev** [comment]
Hey @satwikkansal , could you please close this issue as spam?
