### ISSUE TITLE
Add translation for Portuguese

### ISSUE THREAD

**Issue by pzuehlke** [satwikkansal/wtfpython#289]
Hi satwikkansal, I would like to translate the README section to Portuguese, if possible. I noticed only after initially raising the issue that there is already an open issue regarding this (# 278) by a different user. Could you clarify what the current status of that person's work is before I commit myself to the translation? If the user who had raised the issue is already working on it, I think it would be better if you deleted this issue (i.e., the one that I have raised). Otherwise, I am available to work on the translation. In this case, here is the info requested in the template: Expected duration: 3 months. I'll start working on it within 5 days. Best regards.

**Comment by satwikkansal** [comment]
Hi @pzuehlke 

Thanks for considering! I have followed up with the #278 author (by the looks of his fork it seems he hasn't started), I'd recommend that if we don't get a response within 5 days, feel free to go ahead and start the translation :)

**Comment by pzuehlke** [comment]
Hi @satwikkansal ,

Great, thanks for the quick reply! Let's proceed as you suggested.

**Comment by pzuehlke** [comment]
Hi again @satwikkansal, I noticed that the author of issue #278 replied last Friday that he is almost finished with the translation, so I am closing this issue. Best regards!

**Comment by satwikkansal** [comment]
@pzuehlke I see, just checked that, thank you anyway for considering translating this project :)
