### ISSUE TITLE
How NOT to create nested lists

### ISSUE THREAD

**Issue by danielfleischer** [satwikkansal/wtfpython#291]
I have a nice example which confused me in the past; it's probably a corollary of some other examples already here but it's so simple I think it's worth presenting. 

Here's a bad way of creating a nested list:
```python
a = [[]] * 5
a[0].append(4)
print(a)
```

My expectation was 
```python
[[4],[],[],[],[]]
``` 
but of course the answer is 
```python
[[4],[4],[4],[4],[4]]
``` 
because `[]` is the same object. 

A better way to create a nested list is using list comprehension:

```python
a = [[] for _ in range(5)]
```

I can create patch to present this. What do you think?

**Comment by satwikkansal** [comment]
Hi, thanks for the suggestion!

I think this is mostly covered in https://github.com/satwikkansal/wtfpython#-a-tic-tac-toe-where-x-wins-in-the-first-attempt

**Comment by danielf-amobee** [comment]
Oops, I missed it when scanning for similar patterns. 

Feel free to close. Thanks!

**Comment by satwikkansal** [comment]
Thanks, appreciate the effort :)
