### ISSUE TITLE
email links for NL and ebook not working

### ISSUE THREAD

**Issue by carloocchiena** [satwikkansal/wtfpython#294]
Seems like both forms for pdf version and email subs are not working.
the button on the form seems to be literally not clickable
tried with many emails address and browser (chrome brave edge)
I'm opening an issue since a) i'd like to subscribe b) probably you are losing good leads

**Comment by satwikkansal** [comment]
Yikes, I just realised they've been dead since 2021 Feb!! So now missing more than a year worth of people who might have been interested :( 

Anyways, thanks so much for highlighting it, I have fixed the links, and they should be functioning fine now.

Let me know if it still isn't working :)

**Comment by carloocchiena** [comment]
Now it's fine and working! thank you!
