### ISSUE TITLE
Add translation for Russian

### ISSUE THREAD

**Issue by frontdevops** [satwikkansal/wtfpython#297]
Expected time to finish: 2 weeks. I'll start working on it from next week.

**Comment by satwikkansal** [comment]
Hey @frontdevops 

Thanks for considering translating the project to Russian. Please check https://github.com/satwikkansal/wtfpython/issues/118 , some people have attempted it, so I think you can get a headstart from their forks :) 

Let me know if you need any help.

**Comment by frontdevops** [comment]
Hi! I started translating. I looked up issue 118. It's from 2019. And since the translation still doesn't exist - I'd like to finish it and send a pool requester. I've already started. I hope to finish it as planned.

https://github.com/frontdevops/wtfpython

**Comment by satwikkansal** [comment]
Got it, looking forward to it!

**Comment by frontdevops** [comment]
I translate 50% of all
And I continue... ;)

https://github.com/frontdevops/wtfpython

**Comment by nifadyev** [comment]
Hey @frontdevops, are you planning to finish the translation? I'd love to help and make this super useful Python gotchas available for russian speaking devs. Or I can finish what you've already done if case you're not interested in completing the task.

**Comment by satwikkansal** [comment]
Hi @nifadyev looks like @frontdevops is away, feel free to take it up if you like :)

**Comment by satwikkansal** [comment]
Great, looking forward to it :)

**Comment by frontdevops** [comment]
Hi! Yes, I'll finish it this week, I haven't posted the translation, I've been busy. The translation is there, I just need to commit.

**Comment by nifadyev** [comment]
Awesome, then I can review your translation, if you'd like

**Comment by nifadyev** [comment]
Hey @frontdevops , any progress on pushing commits with new translations? Do you need help with reviewing?

**Comment by frontdevops** [comment]
Hey. I just wanted to let you know that I'm releasing new updates little by little, and there are new commits that you can check out. I'm making some good progress, so thanks for asking!

**Comment by nifadyev** [comment]
Awesome, then I will start reviewing this week. What's the most suitable way: use this PR or leave comments in your fork?

**Comment by eartqk** [comment]
Hi @frontdevops, is there any updates on this? Do you need any help? I can help with the translation and also can do a review too

**Comment by satwikkansal** [comment]
Hi @eartqk 

You can find his fork at https://github.com/frontdevops/wtfpython 

I think @frontdevops isn't getting a chance to get to it, so feel free to take it forward if you like :)

**Comment by nifadyev** [comment]
Hey @satwikkansal ,

As discussed by email, I'm starting the translation based on existing [one](https://github.com/frontdevops/wtfpython)

What do you think about such workflow:
- Store translations in main repository (not in forks like now)
- Create PR in order to check progress and ask for reviews
- Close duplicated [issue](https://github.com/satwikkansal/wtfpython/issues/118) for translation

**Comment by nifadyev** [comment]
Awesome, thanks @satwikkansal

**Comment by nifadyev** [comment]
Hey @eartqk , if you're still interested in translation, please review my PR. It will definitely improve translation quality
