### ISSUE TITLE
Typo in [Strings and the backslashes], missing right parenthesis

### ISSUE THREAD

**Issue by LeonDong1993** [satwikkansal/wtfpython#311]
In section Strings and the backslashes, for the explanations, 2nd point with one of the examples as follows
>  print(repr(r'wt\\"f')
'wt\\\\"f'

I think the right parenthesis is missing here.  It should be 
print(repr(r'wt\\"f') **)**
'wt\\\\"f'

p.s.  I am not sure if others had already bring up this issue, I tried search over existing issues, but I don't find anything related, so i bring it up here.

**Comment by satwikkansal** [comment]
Correct, nice catch, will fix this in next update, thanks @LeonDong1993 !

**Comment by LeonDong1993** [comment]
Thank you for your reply, I think I will just close this issue then ?

**Comment by satwikkansal** [comment]
Let's leave it open :)

**Comment by nifadyev** [comment]
Hey @satwikkansal , could you explain why this issue is still open? The problem has been fixed already [source code](https://github.com/satwikkansal/wtfpython/blob/master/README.md#L1367)

**Comment by satwikkansal** [comment]
oh okay, nice catch, closing it 👍
