### ISSUE TITLE
Create application 


### ISSUE THREAD

**Issue by Nelshonilios** [satwikkansal/wtfpython#328]

**Comment by nifadyev** [comment]
Hey @Nelshonilios , could you provide detailed description of this issue if it is still relevant for you?

**Comment by Nelshonilios** [comment]
Yes

Le lun. 14 oct. 2024, 12:24, Vadim Nifadev ***@***.***> a
écrit :

**Comment by satwikkansal** [comment]
closing this due to insufficient information, feel free to reopen if needed.
