### ISSUE TITLE
G

### ISSUE THREAD

**Issue by Francescooooooooooooo** [satwikkansal/wtfpython#331]
H

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Accessori Auto Shop</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <h1>Accessori Auto Shop</h1>
        <nav>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">Prodotti</a></li>
                <li><a href="#">Contatti</a></li>
            </ul>
        </nav>
    </header>

    <section id="main-content">
        <h2>Benvenuto nel nostro negozio di accessori auto!</h2>
        <p>Scopri la nostra vasta selezione di accessori per auto.</p>
        
    </section>

    <footer>
        <p>&copy; 2024 Accessori Auto Shop. Tutti i diritti riservati.</p>
    </footer>
</body>
</html>

**Comment by Francescooooooooooooo** [comment]
body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
}

header {
    background-color: #333;
    color: #fff;
    padding: 20px;
}

header h1 {
    margin: 0;
}

nav ul {
    list-style-type: none;
    padding: 0;
}

nav ul li {
    display: inline;
    margin-right: 20px;
}

nav ul li a {
    color: #fff;
    text-decoration: none;
}

#main-content {
    padding: 20px;
}

footer {
    background-color: #333;
    color: #fff;
    text-align: center;
    padding: 10px 0;
}

**Comment by nifadyev** [comment]
Hey @satwikkansal , should this issue be closed as spam?
