### ISSUE TITLE
Add markdown linter and formatter

### ISSUE THREAD

**Issue by nifadyev** [satwikkansal/wtfpython#347]
Current `README.md` does not follow any `markdown` convention formats. The project should choose a `markdown` flavor and stick to it with the help of linter/formatter

**Comment by satwikkansal** [comment]
We can configure this Github action https://github.com/DavidAnson/markdownlint-cli2-action , and as for the flavor we can go with https://github.github.com/gfm/

Open to other suggestions as well!
