### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by Lucas-C** [satwikkansal/wtfpython#36]
Hi.

Just a few "gotcha" suggestions from my personal collection ^^
Tell me which ones are worth a PR:
```
i = 0; a = ['', '']
i, a[i] = 1, 10
print a  # -> ['', 10] - cf. https://news.ycombinator.com/item?id=8091943 - Original blog post from http://jw2013.github.io

issubclass(list, object) # True
issubclass(object, collections.Hashable) # True
issubclass(list, collections.Hashable) # False - There are 1449 such triplets (4.3% of all eligible triplets) in Python 2.7.3 std lib

# Python 2 only, found it myself
f = 100 * -0.016462635 / -0.5487545  # observed on the field, in a real-world situation
print '            f:', f              # 3.0
print '       int(f):', int(f)         # 2
print '     floor(f):', floor(f)       # 2.0

# Name mangling:
class Yo(object):
    def __init__(self):
        self.__bitch = True
Yo().__bitch  # AttributeError: 'Yo' object has no attribute '__bitch'
Yo()._Yo__bitch  # True

class O(object): pass
O() == O()             # False
O() is O()             # False
hash(O()) == hash(O()) # True !
id(O()) == id(O())     # True !!!
# ANSWER: http://stackoverflow.com/a/3877275/636849

json.loads('[NaN]') # [nan]
json.loads('[-Infinity]') # [-inf]

int('١٢٣٤٥٦٧٨٩') # 123456789 - cf. http://chris.improbable.org/2014/8/25/adventures-in-unicode-digits/

# Implicit type conversion of keys in dicts
d = {'a':42}
print type(d.keys()[0]) # str
class A(str): pass
a = A('a')
d[a] = 42
print d # {'a':42}
print type(d.keys()[0]) # str

# Those final ones are taken from cosmologicon Python wats quiz
'abc'.count('') == 4
1000000 < '' and () > []  # "objects of different types except numbers are ordered by their type names"
False == False in [False]

[3,2,1] < [1,3]  # False
[1,2,3] < [1,3]  # True

x, y = (0, 1) if True else None, None # -> ((0, 1), None)
x, y = (0, 1) if True else (None, None) # -> (0, 1)
```

**Comment by satwikkansal** [comment]
Hey, thanks for the suggestions. I must say some of them are really cool and unique.

```py
i = 0; a = ['', '']
i, a[i] = 1, 10
print a  # -> ['', 10] - cf. https://news.ycombinator.com/item?id=8091943 - Original blog post from http://jw2013.github.io
```
This one seems similar to https://github.com/satwikkansal/wtfpython#lets-see-if-you-can-guess-this

```py
issubclass(list, object) # True
issubclass(object, collections.Hashable) # True
issubclass(list, collections.Hashable) # False - There are 1449 such triplets (4.3% of all eligible triplets) in Python 2.7.3 std lib
```
This actually felt weird to me initially, ( It is kinda expected for `issubclass` method to hold transitivity relationships). Anyways, I found an [explanation](https://www.naftaliharris.com/blog/python-subclass-intransitivity/) for this as well and it seems like a good example to add to the collection.

**Comment by satwikkansal** [comment]
```py
# Python 2 only, found it myself
f = 100 * -0.016462635 / -0.5487545  # observed on the field, in a real-world situation
print '            f:', f              # 3.0
print '       int(f):', int(f)         # 2
print '     floor(f):', floor(f)       # 2.0
```
Whoa, that `3.0` in the output is confusing me. Is it because of the floating point structure (just a guess)?
By the way, this also seems to be a good example to have if we have the reason of why it works just in Python2 and what causes it.

**Comment by satwikkansal** [comment]
```py
# Name mangling:
class Yo(object):
    def __init__(self):
        self.__bitch = True
Yo().__bitch  # AttributeError: 'Yo' object has no attribute '__bitch'
Yo()._Yo__bitch  # True
```
This one is super cool :sunglasses:

**Comment by satwikkansal** [comment]
```py
class O(object): pass
O() == O()             # False
O() is O()             # False
hash(O()) == hash(O()) # True !
id(O()) == id(O())     # True !!!
# ANSWER: http://stackoverflow.com/a/3877275/636849
```

I was also planning to add similar examples related to memory allocation in Python. Here's another snippet one on the similar lines that I found on the internet
```py
import numpy as np

def aether_send(x): 
    np.array([float(x)])

def aether_receive(): 
    return np.empty((), dtype=np.float).tolist()

aether_send(123.456)
aether_receive() # 123.456...usually.
```
[Source](https://www.reddit.com/r/Python/comments/6x6upn/wtfpython_a_collection_of_interesting_and_tricky/dme96dq/)

These are definitely worth adding :+1:

**Comment by satwikkansal** [comment]
```py
json.loads('[NaN]') # [nan]
json.loads('[-Infinity]') # [-inf]
```
um, why do you think it's a wtf? I feel like this is just a more polished behavior for a function like `json.loads`.

**Comment by satwikkansal** [comment]
```py
int('١٢٣٤٥٦٧٨٩') # 123456789 - cf. http://chris.improbable.org/2014/8/25/adventures-in-unicode-digits/
```
This seems good to add to the [Minor ones](https://github.com/satwikkansal/wtfpython#minor-ones) collection.

**Comment by satwikkansal** [comment]
```py
# Implicit type conversion of keys in dicts
d = {'a':42}
print type(d.keys()[0]) # str
class A(str): pass
a = A('a')
d[a] = 42
print d # {'a':42}
print type(d.keys()[0]) # str
```
This can be added to minor ones as well.

```py
'abc'.count('') == 4
1000000 < '' and () > []  # "objects of different types except numbers are ordered by their type names"
```
Both of them are also good for the Minor ones collection.

```
False == False in [False]
```
This can be added to the snippet in https://github.com/satwikkansal/wtfpython#be-careful-with-chained-operations

```
[3,2,1] < [1,3]  # False
[1,2,3] < [1,3]  # True
```
hmm, I don't think it's a wtf, just a nice high level functionality to have, but still if you think that most of the people would find it as an unexpected behavior, then we can add this to the Minor ones as well!

**Comment by satwikkansal** [comment]
Phew... @Lucas-C Thank you so much for sharing these gems. I'm a little stuck with my campus placements right now, otherwise I'd started to work on them straight away. 

However, if you'll be able to manage some time to work on this issue, feel free to take it up and submit patches :)

**Comment by Lucas-C** [comment]
Same for me :)
I just wanted to quickly share those snippets on this great repo,
but won't have time to send a PR before next month :(

**Comment by satwikkansal** [comment]
Ah, never mind, I'll work on them one by one, whenever I get time :+1:

**Comment by asottile** [comment]
> ```
> json.loads('[NaN]') # [nan]
> json.loads('[-Infinity]') # [-inf]
> ```
>
> um, why do you think it's a wtf? I feel like this is just a more polished behavior for a function like json.loads.

NaN and Infinity, while valid floats are not part of the json spec:

```js
> JSON.stringify([NaN, Infinity, -Infinity])
"[null,null,null]"
```

**Comment by satwikkansal** [comment]
Ah, I didn't knew that :(, then it's definitely worth adding :)

**Comment by satwikkansal** [comment]
Alright, time to make the collection more awesome 🚀

**Comment by satwikkansal** [comment]
Thank you so much @Lucas-C  again for sharing them.
