### ISSUE TITLE
Some Unicode characters look identical to ASCII ones

### ISSUE THREAD

**Issue by bastiaan85** [satwikkansal/wtfpython#39]
In the 'Skipping lines' example (the first one), the following explanation is given as to why the two 'value' variables name aren't the same:

> Some Unicode characters look identical to ASCII ones, but are considered distinct by the interpreter.

Imho this paints the wrong picture. ASCII is an encoding, Unicode is a character collection. ASCII isn't a synonym for [the English alphabet](https://en.wikipedia.org/wiki/English_alphabet). In Python 3, all strings are Unicode, it has lost the relation to any legacy encoding, and ASCII will fall more and more into disuse. The point the example tries to make is that certain Unicode characters are homoglyphs, and that those homoglyphs to an English alphabet character can provide a pitfall for an agnostic reader. I think it should read something like:

> Some non-Western characters look identical to letters in the English alphabet, but are considered distinct by the interpreter. For example the Cyrillic 'е' (Ye) and the Latin 'e', which can be demonstrated by using the built-in `ord()` function, that returns a character's Unicode code point:

Then also the second  code snippet can feature an actual different example than the first one instead of repeating the same value = something:

```py
>>> ord('е') # cyrillic Ye
1077
>>> ord('e') # latin, as used in English
101
>>> 'е' == 'e'
False
```

**Comment by satwikkansal** [comment]
Agreed. Your explanation is more accurate and the example seems to be more relevant to the explanation. Will update this soon. :+1:

**Comment by satwikkansal** [comment]
Hey @bastiaan85, Thank you so much for pointing this out. 76da1b8 has the changes as per your suggestions, feel free to reopen the issue if something is incorrect or missing :)

**Comment by bastiaan85** [comment]
@satwikkansal : you're welcome, glad to be of help :)
