### ISSUE TITLE
Half triple-quoted strings

### ISSUE THREAD

**Issue by asottile** [satwikkansal/wtfpython#40]
https://github.com/asottile/wat/blob/303ea23f916dace0816ab521d3d11ed50bf0d6bb/python/half_triple_quoted_strings.py#L1-L5

Explain: implicit string joining

There's a few others in there that this repository already seems to have, nice collection :)

**Comment by satwikkansal** [comment]
Thanks @asottile, will add this in next iteration :+1: I went through some examples in your repository, seems interesting, would definitely like to go through in depth sometime and add the missing ones here (after your permission, of course).

**Comment by asottile** [comment]
By all means go for it!
