### ISSUE TITLE
discrepancy about "Evaluation time discrepancy"

### ISSUE THREAD

**Issue by zxdvd** [satwikkansal/wtfpython#41]
Hi,

I am testing about the interesting **Evaluation time discrepancy**, and I have a test like following:
```
a = [1, 2, 3]
b = [10, 20, 30]
g = (i + j for i in a for j in b)
a = [4, 5, 6]
b = [100, 200, 300]
print(list(g))
```
And the result is
```
[101, 201, 301, 102, 202, 302, 103, 203, 303]
```
I tested it with python3 on osx and debian, and got same result.

It seems that only *a* is **evaluated at declaration time**? Or passed by reference?
Could someone give some detailed information about this?

**Comment by zxdvd** [comment]
I digged a little about this and found something from generated byte code.
```
a = [1, 2, 3]
b = [10, 20, 30]
g = (i + j for i in a for j in b if 4 in a and 100 in b)
a = [4, 5, 6]
b = [100, 200, 300]
import dis
dis.dis(g)
```

result
```
  1           0 LOAD_FAST                0 (.0)
        >>    3 FOR_ITER                52 (to 58)
              6 STORE_FAST               1 (i)
              9 LOAD_GLOBAL              0 (b)
             12 GET_ITER
        >>   13 FOR_ITER                39 (to 55)
             16 STORE_FAST               2 (j)
             19 LOAD_CONST               0 (4)
             22 LOAD_GLOBAL              1 (a)
             25 COMPARE_OP               6 (in)
             28 POP_JUMP_IF_FALSE       13
             31 LOAD_CONST               1 (100)
             34 LOAD_GLOBAL              0 (b)
             37 COMPARE_OP               6 (in)
             40 POP_JUMP_IF_FALSE       13
             43 LOAD_FAST                1 (i)
             46 LOAD_FAST                2 (j)
             49 BINARY_ADD
             50 YIELD_VALUE
             51 POP_TOP
             52 JUMP_ABSOLUTE           13
        >>   55 JUMP_ABSOLUTE            3
        >>   58 LOAD_CONST               2 (None)
             61 RETURN_VALUE
```

It seems that only the first `for i in X` is loaded from local scope(LOAD_FAST),  all other `for x in XX` and `if XX` are loaded from global scope(LOAD_GLOBAL).

**Comment by satwikkansal** [comment]
Hey @zxdvd, that's a nice question (and sorry for extremely delayed response). I don't have much familiarity with assembly level codes, but I think you're right about `for i in x` being loaded from global scope and `for x in y` and `if y` being loaded from global scope.

Anyways, I'll keep this issue open while I try to read more about it or maybe someone familiar with this who can confirm/correct it.

**Comment by sohaibfarooqi** [comment]
@zxdvd  Yes your analysis is correct. According to [PEP-289](https://www.python.org/dev/peps/pep-0289/#the-details)
   > Only the outermost for-expression is evaluated immediately, the other expressions are deferred until the generator is run

You can visit the link to get some more insights and details.

**Comment by satwikkansal** [comment]
Added a snippet and releveant explanation for this in the project. Feel free to check out the above commit and revert back if anything's incorrect / missing.
