### ISSUE TITLE
Unable to replicate Skipping lines

### ISSUE THREAD

**Issue by rohithasrk** [satwikkansal/wtfpython#49]
Which version of python has this been tested on? I'm unable to replicate it on python 2.7

**Comment by satwikkansal** [comment]
Hey, you need to copy-paste those statements directly into your file/terminal and it should work.

**Comment by rohithasrk** [comment]
Shows this.
![yes i did](https://user-images.githubusercontent.com/13820931/31816908-b9dffe6e-b5af-11e7-8ed3-808eee5569ab.png)

**Comment by satwikkansal** [comment]
Well, are you sure that you copied the lines directly from the example in the README.md, because it should work then.

**Comment by rohithasrk** [comment]
Okay. Got it. Thanks
