### ISSUE TITLE
Cannot reproduce "wtf"*bool example

### ISSUE THREAD

**Issue by Plumbob** [satwikkansal/wtfpython#57]
In [Part 3 of  "What is wrong with booleans?"](https://github.com/satwikkansal/wtfpython#-whats-wrong-with-booleans) there's the following example:

    >>> some_bool = True
    >>> "wtf"*some_bool
    'wtf'
    >>> "wtf"*some_bool
    ''

I'm unable to reproduce this with either 2.7.10 nor 3.6.4:

    Python 2.7.10 (default, Jul 15 2017, 17:16:57) 
    IPython 5.5.0 -- An enhanced Interactive Python.
    
    In [1]: some_bool = True

    In [2]: "wtf"*some_bool
    Out[2]: 'wtf'

    In [3]: "wtf"*some_bool
    Out[3]: 'wtf'    

    Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28)
    IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

    In [1]: some_bool = True

    In [2]: "wtf"*some_bool
    Out[2]: 'wtf'

    In [3]: "wtf"*some_bool
    Out[3]: 'wtf'

Great work collecting all these examples.  Thank you for doing this.

**Comment by satwikkansal** [comment]
Oh, that's my fault actually. It's missing a statement `some_bool = False`. Fixed it right away! Thanks for pointing it out @Plumbob  and I'm glad that you liked the project.
