### ISSUE TITLE
Consume generator expression after updating the iterable

### ISSUE THREAD

**Issue by sohaibfarooqi** [satwikkansal/wtfpython#63]
Hi,
I have submitted a [PR](https://github.com/satwikkansal/wtfpython/pull/61) for which I want input from the community. Let me summarise the code example that I have submitted:

     >>>  iter1 = [1,2,3,4]
      >>> g1 = (x for x in iter1)
      >>> iter1 = [1,2,3,4,5]
      >>> list(g1)
      >>> [1,2,3,4]

      >>> iter2 = [1,2,3,4]
      >>> g2 = (x for x in iter2)
      >>> iter2[:] = [1,2,3,4,5] 
      >>> list(g2)
      >>> [1,2,3,4,5]

This is basically consuming the generator after updating the provided iterable. The main difference in two examples in mainly how they updated the elements of iterable. First one uses `=`(Assignment Operator) and second one used `[:]=`(Slice Assignment). Assignment creates a new list thats why output of generator is not changed, whereas slice assignment updated the list iteself thats why generator outputs the updated list.

@satwikkansal suggested that [Evaluation time discrepancy](https://github.com/satwikkansal/wtfpython#-evaluation-time-discrepancy) is similar to the one 
I submitted and asked me to open an issue so that we can have discussion on this one.

What do you guys think? Any suggestions/improvements/critique?

Thanks,
Sohaib

**Comment by satwikkansal** [comment]
Hey @sohaibfarooqi I think we should add this to the collection anyway (sorry if I came across as pompous at that time).
