### ISSUE TITLE
Add this to the explanation in "https://github.com/satwikkansal/wtfpython#-backslashes-at-the-end-of-string"

### ISSUE THREAD

**Issue by shashank1094** [satwikkansal/wtfpython#69]
From SO post - https://stackoverflow.com/questions/647769/why-cant-pythons-raw-string-literals-end-with-a-single-backslash

> String quotes can be escaped with a backslash, but the backslash remains in the string; for example, r"\"" is a valid string literal consisting of two characters: a backslash and a double quote; r"\" is not a valid string literal (even a raw string cannot end in an odd number of backslashes). Specifically, a raw string cannot end in a single backslash (since the backslash would escape the following quote character). Note also that a single backslash followed by a newline is interpreted as those two characters as part of the string, not as a line continuation.

Few examples : 

```
>>> print(r"\"")
\"
>>> print(r"A\nB")
A\nB
>>> print(r"A\\nB")
A\\nB
>>> print("A\nB")
A
B
>>> print("A\\nB")
A\nB
>>> print("A\\\nB")
A\
B
```

**Comment by ashish4321** [comment]
Can i work on it?

**Comment by ashish4321** [comment]
Are you active??

**Comment by satwikkansal** [comment]
Updated the explanation, thanks @shashank1094 :) You can check the above commit and let me know if something's incorrect / missing.
