### ISSUE TITLE
https://github.com/satwikkansal/wtfpython#-not-knot  doubt in operator precedence

### ISSUE THREAD

**Issue by shashank1094** [satwikkansal/wtfpython#70]
According to [Python docs ](https://docs.python.org/3/reference/expressions.html#operator-precedence) the **Boolean NOT**  has higher precedence than **Comparisons**. But the output you have shown is correct so what an I misinterpreting?

**Comment by sohaibfarooqi** [comment]
You are misinterpreting the docs:
> The following table summarizes the operator precedence in Python, from lowest precedence (least binding) to highest precedence (most binding)

The table is in ascending order, means operator which appears first have low precedence than the one which appear below. `not` appears above `==`, so **BOOLEAN NOT** has lower precedence than `==`.
