### ISSUE TITLE
return or break statement in a finally block

### ISSUE THREAD

**Issue by koddo** [satwikkansal/wtfpython#73]
Hello. What do you think, is the following a wat?

<https://docs.python.org/3/reference/compound_stmts.html#the-try-statement>:

> If an exception occurs in any of the clauses and is not handled, the exception is temporarily saved. ... If the finally clause executes a return or break statement, the saved exception is discarded.

Example:

``` Python
while True:
    try:
        1/0
    except Exception:
        raise
    finally:
        break     # discards the exception

print('hell')     # it does print indeed
```

**Comment by satwikkansal** [comment]
Hey @koddo

That's interesting. Thanks for sharing it. I'd be adding this in the next iteration (or you can submit a PR if you like)

**Comment by shashank1094** [comment]
Hell is getting printed. I am using Python 3.6.4.

**Comment by satwikkansal** [comment]
Added to the collection, thanks again!
