### ISSUE TITLE
Include example of OrderedDict's intransitive __eq__ implementation?

### ISSUE THREAD

**Issue by jab** [satwikkansal/wtfpython#77]
The second snippet in https://github.com/cosmologicon/pywat/issues/38 provides an example of such a big WTF in Python that Raymond Hettinger himself even called OrderedDict's intransitive equality a mistake. Any interest in including that here?

**Comment by jab** [comment]
![screen shot 2018-04-26 at 16 29 11](https://user-images.githubusercontent.com/64992/39297967-1ebdd9a2-496f-11e8-81df-a5139512ee42.png)

> This allows OrderedDict objects to be substituted anywhere a regular dictionary is used.

Well, not exactly *anywhere*, as my `od == od2` example from https://github.com/cosmologicon/pywat/issues/38 demonstrates. This imprecision is a bug in the docs. An edge case bug, but still a bug.

**Comment by chris-rands** [comment]
Interesting thanks, I guess that *either way* the behaviour would surprise some users. I'm not convinced this is a doc bug, but file it as one if you think so https://bugs.python.org/

**Comment by satwikkansal** [comment]
Thanks for suggesting this @jab , this was actually one of very few genuine WTFs I've observed. Added in the above commit ^^, feel free to have a look and point out any corrections / missing details.
