### ISSUE TITLE
''.split() != ''.split(' ')

### ISSUE THREAD

**Issue by koddo** [satwikkansal/wtfpython#80]
Hello. Does the following qualify?
When you split an empty string without arguments, you get an empty list.
When you specify a separator, you get a non-empty list, see below.
More of an inconsistency than a wtf, but nevertheless I'd like to share this.
I wonder why it works this way.

```
>>> ''.split() != ''.split(' ')
>>> True

>>> ''.split() 
>>> []

>>> ''.split(' ')
>>> ['']
```

**Comment by snahor** [comment]
I don't think so, the docs are pretty clear about what happens when you don't supply a delimiter.

**Comment by satwikkansal** [comment]
umm, I think this can be added to our "Minor ones" collection (I wasn't expecting it to return `['']`)

But let's wait for more opinions on this...

**Comment by lavishsaluja** [comment]
I don't think there is any inconsistency, the [https://docs.python.org/2.7/library/stdtypes.html#str.split](split docs) clearly explains what happens when we pass an empty string and what happens when you pass an empty string with a delimiter.
Also, the very first slack answer [https://stackoverflow.com/questions/16645083/when-splitting-an-empty-string-in-python-why-does-split-return-an-empty-list](Split return on the empty argument) pretty much explains the working of the split.

**Comment by koddo** [comment]
I've just read the stackoverflow answer, and I'm not convinced. I don't understand why with no `sep` an empty string is considered a run of consecutive whitespaces and gets eaten.

> Note, the number of result fields is one greater than the number of delimiters.

To me this should apply to both algorithms.

**Comment by koddo** [comment]
And there's another edge case when a string only consists of whitespace. Should `'         '.split()` return `['', '']` for consistency? Like `','.split(',') == ['', '']` does? Now it returns `[]` like `''.split()`. I don't know. To me this behavior is not obvious.

**Comment by koddo** [comment]
I'm sorry for spamming, I think I get it now.

The non-obvious thing about this function is when there's no `sep` the number of result fields is _one less_ than the number of actual delimiters: both `' a '` and `'a'` have two delimiters and splitting them will result in one field. And with `sep` given the number of result fields is _one more_ than the number of actual delimiters: `','` has one delimiter and splitting will result in two fields.

So the edge case when the string is empty works like this: `''.split()` will have zero fields because the number of delimiters is one, while `''.split(' ')` will have one field because the number of delimiters is zero.

I'd have two functions with carefully chosen names than having one function with behavior like this.

**Comment by satwikkansal** [comment]
@koddo  Added, thanks for the suggestion :) You can check the above commit and let me know if something's incorrect or missing.
