### ISSUE TITLE
Output of "A tic-tac-toe where X wins in the first attempt!" is wrong.

### ISSUE THREAD

**Issue by iBug** [satwikkansal/wtfpython#81]
[Link here](https://github.com/satwikkansal/wtfpython#-a-tic-tac-toe-where-x-wins-in-the-first-attempt)

The last paragraph of the section claims the following output:

```python
>>> board = [(['']*3)*3] # board = = [['']*3 for _ in range(3)]
>>> board[0][0] = "X"
>>> board
[['X', '', ''], ['', '', ''], ['', '', '']]
```

However, the results I get from Python 2.7.15rc1 (Ubuntu 18.04), Python 3.6.5 (Ubuntu 18.04) and Python 3.5.2 (Ubuntu 16.04) are all the same and are different from what this doc days. It is:

```python
[['X', '', '', '', '', '', '', '', '']]
```

Furthermore, I tried multiple ways of arranging the parentheses and couldn't get the said result. All results I have are

```python
>>> board
[['X', '', ''], ['X', '', ''], ['X', '', '']]
```

**Comment by satwikkansal** [comment]
Hi @iBug 

Thanks a lot for pointing this out. I see that there are a couple of issues,

1. `board = [(['']*3)*3]` should have been `board = [['']*3]*3` to get the same output.
2. Even if we use `board = [['']*3]*3`, it is equivalent to same list being referenced three times, so the right way to do it probably is `[['']*3 for _ in range(3)]`
