### ISSUE TITLE
problem in "The mysterious key type conversion" explanation

### ISSUE THREAD

**Issue by book987** [satwikkansal/wtfpython#84]
At last point
* For the desired behavior, we can redefine the `__eq__` method in `SomeClass`
  ```py
  class SomeClass(str):
    def __eq__(self, other):
        return (
            type(self) is SomeClass
            and type(other) is SomeClass
            and super().__eq__(other)
        )

    # When we define a custom __eq__, Python stops automatically inheriting the
    # __hash__ method, so we need to define it as well
    __hash__ = str.__hash__

  some_dict = {'s':42}
  ```

  **Output:**
  ```py
  >>> s = SomeClass('s')
  >>> some_dict[s] = 40
  >>> some_dict
  {'s': 40}
  >>> keys = list(some_dict.keys())
  >>> type(keys[0]), type(keys[1])
  (__main__.SomeClass, str)
  ```
`some_dict` output `{'s': 42, 's': 40}` in Python 3.6.5/3.5.5/3.4.8/2.7.15, can someone provide which version output `{'s': 40}`?

**Comment by book987** [comment]
@satwikkansal It's wrong since added.
we can subclass built-in types since Python-2.2 <sup>[ref](https://docs.python.org/3/whatsnew/2.2.html#peps-252-and-253-type-and-class-changes)</sup>, and the code above output 
```python
Python 2.2.3 (#1, Jun 14 2018, 17:54:08) 
[GCC 8.1.1 20180531] on linux4
Type "help", "copyright", "credits" or "license" for more information.
>>> class SomeClass(str):
... 	def __eq__(self, other):
... 		return (
... 			type(self) is SomeClass
... 			and type(other) is SomeClass
... 			and super().__eq__(other)
... 		)
... 	__hash__ = str.__hash__
... 
>>> some_dict = {'s':42}
>>> s = SomeClass('s')
>>> some_dict[s] = 40
>>> some_dict
{'s': 42, 's': 40}
```

**Comment by satwikkansal** [comment]
@book987 Thanks for pointing it out. I acknowledge that the output is wrong and it should have been `{'s': 42, 's': 40}` (and I've fixed that with recent commit), but I think the explanation is fair enough. What do you think?

**Comment by book987** [comment]
@satwikkansal yes it's fair enough
