### ISSUE TITLE
Is this organization related to this repository?

### ISSUE THREAD

**Issue by 0x48piraj** [satwikkansal/wtfpython#87]
I wanted to know if the following organization is connected with this project as it seems to have no connection with you, with respect to membership. 

**_https://github.com/wtfpython-web_**

**Comment by satwikkansal** [comment]
Hey @0x48piraj , yes it is (we created that for GSSoC).

And just in case even if it wasn't, it'd have been fine too because wtfpython was "WTFPL" license :wink:

**Comment by satwikkansal** [comment]
Closing it btw, if you have further question, we can continue the discussion at https://github.com/satwikkansal/wtfpython/issues/83 :smile:
