### ISSUE TITLE
Feature Request: Could you add the famous (a, b) = a[b] = {}, 5 please?

### ISSUE THREAD

**Issue by PiaFraus** [satwikkansal/wtfPython#9]
I think this one is great and majority of python developers don't ever manage to guess the correct result of 
this expression:
(a, b) = a[b] = {}, 5

https://stackoverflow.com/questions/32127908/python-assignment-operator-precedence-a-b-ab-5

**Comment by satwikkansal** [comment]
Yeah, this seems like "Hell of an example?", working on it :+1:

**Comment by satwikkansal** [comment]
Hey @PiaFraus, added this example to the `README.md` in 3cdc9ac Feel free to reopen the issue if you think I missed something. And Thanks for the suggestion :)

**Comment by PiaFraus** [comment]
Nope. That looks great. Thanks.
