### ISSUE TITLE
Charmap codec Error

### ISSUE THREAD

**Issue by AdityaSoni19031997** [satwikkansal/wtfpython#90]
Hi there, thanks for the amazing repository.....
But I am not able to run it on Python 3.6.3 it throws the `Unicode decode error: 'charmap' codec can't decide byte 0x90....`

**Comment by AdityaSoni19031997** [comment]
Like the traceback? I had received this on both the ways, using npm and directly typing `wtfpython`

**Comment by satwikkansal** [comment]
Okay. I'll try to replicate this. It's probably an encoding error.

**Comment by satwikkansal** [comment]
Fixed with https://github.com/satwikkansal/wtfpython/commit/c475cbfe826f2b65d3674f3acf724f14f97c50dc 

Thanks for reporting it!

**Comment by Anvesh2013** [comment]
I am getting the same error. On 1st Aug 2019. I am using python 3.7 and latest pip

**Comment by satwikkansal** [comment]
Ah, sorry, I forgot to make a release back then. I'll make a release and that should fix it.

**Comment by satwikkansal** [comment]
Fixed.
