### ISSUE TITLE
Let's meet Friendly Language Uncle For Life

### ISSUE THREAD

**Issue by true1023** [satwikkansal/wtfpython#94]
The example worked in interpreter but not when I write in a `.py` file.

```py
from __future__ import barry_as_FLUFL
import sys
print(sys.version)
"Ruby" != "Python" #This is OK
```

```py
from __future__ import barry_as_FLUFL
import sys
print(sys.version)
"Ruby" <> "Python" #But this  raise a exception
```

output 1:

```sh
3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
```
output 2:
```sh
  File "test.py", line 4
    "Ruby" <> "Python"
            ^
SyntaxError: invalid syntax
```

**Comment by Shwetago** [comment]
The second one worked for me but the first one doesn't.
I have used IDLE (Python 3.6.5) 
@true1023

**Comment by satwikkansal** [comment]
@true1023 Thanks for reporting this. Seems like this will only work in non-interactive environment. I'll figure out the reason why, and update it in the readme.

**Comment by satwikkansal** [comment]
I've added the explanation in the project. You can check the above commit and let me know if something's incorrect or missing :)
