### ISSUE TITLE
python 3.0+ Ellipsis

### ISSUE THREAD

**Issue by ghost** [satwikkansal/wtfpython#96]
python2:
```py
>>> Ellipsis
Ellipsis
```
python3:
```py
>>> ...
Ellipsis
>>> Ellipsis
Ellipsis
```
`... and pass`
```py
>>> def test():
               ...  # or pass
>>> a = [1, 2, 3, 4, 5]
>>> a.append(a)
>>> print(a)
[1, 2, 3, 4, 5, [...]]
```

**Comment by satwikkansal** [comment]
Hey, thanks for sharing.
There's an [example](https://github.com/satwikkansal/wtfpython#-lets-see-if-you-can-guess-this) that somewhat covers this, but this would be nice to add in to the explanation section of it. Will be doing it in the next update.

**Comment by satwikkansal** [comment]
@ghost Added, thanks for the suggestion :) You can check the above commit and let me know if something's incorrect or missing.
